### ISSUE TITLE
Blue vertical rectangle and rose/red rectangle on player..... and enemies!! - Last OpenBor Plus version

### ISSUE THREAD

**Issue by Grondoval** [whitedragon0000/OpenBOR_PLUS#101]
![Screenshot_2](https://github.com/whitedragon0000/OpenBOR_PLUS/assets/21977362/e9b28072-14dc-4356-a209-afb85434b675)
## Description

At start stage of game it shows a blue vertical rectangle on principal player but in enemies too, and when attack it appears a rose/red rectangle...!

### Reproduce
LOG:

Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27835199488 Bytes ( 26545 MB )
 Used Ram:     7913472 Bytes (     7 MB )

debug:nativeWidth, nativeHeight, bpp, Hz  1920, 1080, 24, 144
Loaded mapping for Keyboard
OpenBoR v4.0 Build 526 (commit hash: 310707e), Compile Date: Jun  5 2023

Game Selected: Paks/Ladies_of_Rage.pak

Loaded mapping for Keyboard
FileCaching System Init......	Enabled
Initializing video............
'data/video.txt' not found.
Initialized video.............	320x240 (Mode: 0)

Loading menu.txt.............	Done!
Loading fonts................	1 2 3 4 5 6 Done!
Timer init...................	Done!
Initialize Sound..............	Done!
Loading sprites..............	Done!
Loading level order..........	Done!
Loading model constants......	Done!
Loading script settings......	Done!
Loading scripts..............	Done!
Loading models...............

Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Cacheing 'Flash' from data/chars/misc/flash.txt
Cacheing 'Shot' from data/chars/misc/shot.txt
Cacheing 'cut' from data/chars/malin/cut.txt
Cacheing 'venom' from data/chars/king/venom.txt
Cacheing 'pow' from data/chars/fio/pow.txt
Cacheing 'pow1' from data/chars/fio/pow1.txt
Cacheing 'light' from data/chars/beth/light.txt
Cacheing 'loader' from data/chars/misc/loader.txt
Cacheing 'dust' from data/chars/misc/dust.txt
Cacheing 'yshadow' from data/chars/yuri/yshadow.txt
Cacheing 'ball' from data/chars/hotaru/ball.txt
Cacheing 'ice' from data/chars/diana/ice.txt
Cacheing 'mai' from data/chars/mai/mai.txt
Cacheing 'athena' from data/chars/athena/athena.txt
Cacheing 'Mball' from data/chars/athena/mball.txt
Cacheing 'killa' from data/chars/beth/killa.txt
Cacheing 'FBoom' from data/chars/misc/fboom.txt
Cacheing 'awave' from data/chars/ash/awave.txt
Cacheing 'ghosts' from data/chars/akari/ghosts.txt
Cacheing 'fire' from data/chars/ai/fire.txt
Cacheing 'King' from data/chars/king/king.txt
Cacheing 'May' from data/chars/may/may.txt
Cacheing 'malin' from data/chars/malin/malin.txt
Cacheing 'elizabeth' from data/chars/beth/beth.txt
Cacheing 'momo' from data/chars/momo/momo.txt
Cacheing 'shion' from data/chars/shion/shion.txt
Cacheing 'shiki' from data/chars/aki/aki.txt
Cacheing 'Apple' from data/chars/misc/apple.txt
Cacheing 'Meat' from data/chars/misc/meat.txt
Cacheing '1up' from data/chars/misc/1up.txt
Cacheing 'Money' from data/chars/misc/money.txt
Cacheing 'Gold' from data/chars/misc/gold.txt
Cacheing 'Time' from data/chars/misc/time.txt
Cacheing 'Box' from data/chars/misc/box.txt
Cacheing 'Crate' from data/chars/misc/crate.txt
Cacheing 'Trash' from data/chars/misc/trash.txt
Cacheing 'Table' from data/chars/misc/table.txt
Cacheing 'Chair' from data/chars/misc/chair.txt
Cacheing 'Fence' from data/chars/misc/fence.txt
Cacheing 'Drum' from data/chars/misc/drum.txt
Cacheing 'Trolly' from data/chars/misc/trolly.txt
Cacheing 'Shermie' from data/chars/shermie/shermie.txt
Cacheing 'Angel' from data/chars/angel/angel.txt
Cacheing 'Judith' from data/chars/judith/judith.txt
Cacheing 'Whip' from data/chars/whip/whip.txt
Cacheing 'Jenet' from data/chars/jenet/jenet.txt
Cacheing 'Char' from data/chars/char/char.txt
Cacheing 'rider' from data/chars/biker/rider.txt
Cacheing 'kula' from data/chars/kula/kula.txt
Cacheing 'mary' from data/chars/mary/mary.txt
Cacheing 'evy' from data/chars/evy/evy.txt
Cacheing 'fio' from data/chars/fio/fio.txt
Cacheing 'fio2' from data/chars/fio2/fio.txt
Cacheing 'hinako' from data/chars/hinako/hinako.txt
Cacheing 'AI' from data/chars/ai/ai.txt
Cacheing 'sarah' from data/chars/sarah/sarah.txt
Cacheing 'jenny' from data/chars/jenny/jenny.txt
Cacheing 'kagura' from data/chars/kagura/kagura.txt
Cacheing 'momoko' from data/chars/momo/momo2.txt
Cacheing 'cmai' from data/chars/cmai/cmai.txt
Cacheing 'mature' from data/chars/mature/mature.txt
Cacheing 'vice' from data/chars/vice/vice.txt
Cacheing 'yuri' from data/chars/yuri/yuri.txt
Cacheing 'ash' from data/chars/ash/ash.txt
Cacheing 'xiang' from data/chars/xiang/xiang.txt
Cacheing 'hotaru' from data/chars/hotaru/hotaru.txt
Cacheing 'leona' from data/chars/leona/leona.txt
Cacheing 'kasumi' from data/chars/kasumi/kasumi.txt
Cacheing 'akari' from data/chars/akari/akari.txt
Cacheing 'foxy' from data/chars/foxy/foxy.txt
Cacheing 'diana' from data/chars/diana/diana.txt
Cacheing 'ashb' from data/chars/ash/ashb.txt
Cacheing 'Knife' from data/chars/misc/knife.txt
Cacheing 'Star' from data/chars/misc/star.txt
Cacheing 'Steam' from data/chars/misc/steam.txt
Cacheing 'Steamer' from data/chars/misc/steamer.txt
Cacheing 'Furnace' from data/chars/misc/furnace.txt
Cacheing 'Arrow' from data/chars/misc/arrow.txt

Loaded 'Flash' from data/chars/misc/flash.txt 
Loaded 'Shot' from data/chars/misc/shot.txt 
Loaded 'cut' from data/chars/malin/cut.txt 
Loaded 'venom' from data/chars/king/venom.txt 
Loaded 'pow' from data/chars/fio/pow.txt 
Loaded 'pow1' from data/chars/fio/pow1.txt 
Loaded 'light' from data/chars/beth/light.txt 
Loaded 'Dust' from data/chars/misc/dust.txt 
Loaded 'YShadow' from data/chars/yuri/yshadow.txt 
Loaded 'ball' from data/chars/hotaru/ball.txt 
Loaded 'ice' from data/chars/diana/ice.txt 
Loaded 'mai' from data/chars/mai/mai.txt 
sound_load_sample can't load sample from file 'data/chars/mai/die.wav'!
sound_load_sample can't load sample from file 'data/chars/mai/spc.wav'!
sound_load_sample can't load sample from file 'Data/Chars/Mai/ryu.wav'!
sound_load_sample can't load sample from file 'data/chars/mai/a.wav'!
Loaded 'Athena' from data/chars/athena/athena.txt 
Loaded 'Mball' from data/chars/athena/mball.txt 
Loaded 'killa' from data/chars/beth/killa.txt 
Loaded 'FBoom' from data/chars/misc/fboom.txt 
sound_load_sample can't load sample from file 'data/sounds/maxboom.wav'!
Loaded 'awave' from data/chars/ash/awave.txt 
Loaded 'ghosts' from data/chars/akari/ghosts.txt 
Loaded 'fire' from data/chars/ai/fire.txt 
Loaded 'king' from data/chars/king/king.txt 
Loaded 'may' from data/chars/may/may.txt 
Loaded 'malin' from data/chars/malin/malin.txt 
Loaded 'elizabeth' from data/chars/beth/beth.txt 
sound_load_sample can't load sample from file 'data/chars/throw.wav'!
sound_load_sample can't load sample from file 'data/chars/throw.wav'!
Loaded 'shion' from data/chars/shion/shion.txt 
Loaded 'shiki' from data/chars/aki/aki.txt 

Loading models...............	Done!
Object engine init...........	Done!
Input init...................	Done!
Create blending tables.......	Done!
Save settings so far........	Done!

Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Level Loading:   'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27768901632 Bytes ( 26482 MB )
 Used Ram:    74657792 Bytes (    71 MB )

Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Loaded '1up' from data/chars/misc/1up.txt 
Loaded 'whip' from data/chars/whip/whip.txt 
Loaded 'angel' from data/chars/angel/angel.txt 
Loaded 'shermie' from data/chars/shermie/shermie.txt 
Loaded 'kagura' from data/chars/kagura/kagura.txt 
Loaded 'Trash' from data/chars/misc/trash.txt 
Loaded 'money' from data/chars/misc/money.txt 
Loaded 'jenet' from data/chars/jenet/jenet.txt 
Loaded 'Meat' from data/chars/misc/meat.txt 
Loaded 'apple' from data/chars/misc/apple.txt 
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.

Level Loaded:    'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27770863616 Bytes ( 26484 MB )
 Used Ram:    76148736 Bytes (    72 MB )
Total sprites mapped: 2156

Level Unloading: 'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27745931264 Bytes ( 26460 MB )
 Used Ram:    76476416 Bytes (    72 MB )

RAM Status:
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27745931264 Bytes ( 26460 MB )
 Used Ram:    76476416 Bytes (    72 MB )

Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Level Loading:   'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27778043904 Bytes ( 26491 MB )
 Used Ram:    76488704 Bytes (    72 MB )

Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.
Warning: Unknown command in lifebar.txt: 'color600'.
Warning: Unknown command in lifebar.txt: 'color700'.
Warning: Unknown command in lifebar.txt: 'color800'.
Warning: Unknown command in lifebar.txt: 'color900'.
Warning: Unknown command in lifebar.txt: 'color1000'.
Warning: Unknown command in lifebar.txt: 'color1100'.
Warning: Unknown command in lifebar.txt: 'color1200'.
Warning: Unknown command in lifebar.txt: 'color1300'.
Warning: Unknown command in lifebar.txt: 'color1400'.
Warning: Unknown command in lifebar.txt: 'color1500'.
Warning: Unknown command in lifebar.txt: 'color1600'.
Warning: Unknown command in lifebar.txt: 'color1700'.
Warning: Unknown command in lifebar.txt: 'color1800'.
Warning: Unknown command in lifebar.txt: 'color1900'.
Warning: Unknown command in lifebar.txt: 'color2000'.
Warning: Unknown command in lifebar.txt: 'color2100'.
Warning: Unknown command in lifebar.txt: 'color2200'.
Warning: Unknown command in lifebar.txt: 'color2300'.

Level Loaded:    'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27795116032 Bytes ( 26507 MB )
 Used Ram:    76488704 Bytes (    72 MB )
Total sprites mapped: 2156

************ Shutting Down ************

OpenBOR v4.0 Build 526 (commit hash: 310707e), Compile Date: Jun  5 2023
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27774316544 Bytes ( 26487 MB )
 Used Ram:    76521472 Bytes (    72 MB )

Release level data...........
Level Unloading: 'data/hard/1ahard.txt'
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27774582784 Bytes ( 26487 MB )
 Used Ram:    76001280 Bytes (    72 MB )

RAM Status:
Total Ram: 34287116288 Bytes ( 32698 MB )
 Free Ram: 27774636032 Bytes ( 26487 MB )
 Used Ram:    76001280 Bytes (    72 MB )

Done!

Release graphics data........	Done!
Release game data............

Unload 'Flash' ............Done.
Unload 'Shot' ............Done.
Unload 'cut' ............Done.
Unload 'venom' ............Done.
Unload 'pow' ............Done.
Unload 'pow1' ............Done.
Unload 'light' ............Done.
Unload 'Dust' ............Done.
Unload 'YShadow' ............Done.
Unload 'ball' ............Done.
Unload 'ice' ............Done.
Unload 'mai' ............Done.
Unload 'Athena' ............Done.
Unload 'Mball' ............Done.
Unload 'killa' ............Done.
Unload 'FBoom' ............Done.
Unload 'awave' ............Done.
Unload 'ghosts' ............Done.
Unload 'fire' ............Done.
Unload 'king' ............Done.
Unload 'may' ............Done.
Unload 'malin' ............Done.
Unload 'elizabeth' ............Done.
Unload 'shion' ............Done.
Unload 'shiki' ............Done.
Unload '1up' ............Done.
Unload 'Whip' ............Done.
Unload 'Angel' ............Done.
Unload 'Shermie' ............Done.
Unload 'kagura' ............Done.
Unload 'Trash' ............Done.
Unload 'Money' ............Done.
Unload 'Jenet' ............Done.
Unload 'Meat' ............Done.
Unload 'Apple' ............Done.

Release game data............	Done!
Release timer................	Done!
Release input hardware.......	Done!
Release sound system.........	Done!
Release FileCaching System...	Done!

**************** Done *****************

OpenBOR v4.0 Build 526 (commit hash: 310707e), Compile Date: Jun  5 2023
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

### Version
Please provide the SPECIFIC version the issue first appeared. This is very important, it is nearly impossible for us to pour through the entire code base to find singular issues without a starting point.

Computer/PC/Windows 10: OpenBOR v4.0 Build 526 (commit hash: 310707e), Compile Date: Jun  5 2023

![ladies of rage](https://github.com/whitedragon0000/OpenBOR_PLUS/assets/21977362/b8513b27-2338-4fcc-b5c3-3c7cc8a6ab20)

**Comment by Grondoval** [comment]
i try three more .pak and occurs same problem!

**Comment by whitedragon0000** [comment]
It sounds like you're using old save files. delete the entire save category and try testing. the latest version works fine. what you see is the active debug mode

**Comment by Grondoval** [comment]
I delete entire content from save folder and deactivate all options from debug menu, create a new config file and now all .pak show correctly!

Thanks!
