### ISSUE TITLE
THANK YOU! - arm64 RockPro64

### ISSUE THREAD

**Issue by 2play** [whitedragon0000/OpenBOR_PLUS#103]
Just wanted to say thank you for your work on OpenBOR Plus

I have used your repo to compile an arm64 compatible binary fully working on RockPro64.

Not an issue, Just thank you so now ppl can have OpenBOR Plus 4 on arm64 

Kind regards,
2Play
![Screenshot from 2023-12-07 12-17-45](https://github.com/whitedragon0000/OpenBOR_PLUS/assets/30235736/1a405e4c-a1f2-469e-be3e-08c1e9436072)

**Comment by whitedragon0000** [comment]
thanks man!
