### ISSUE TITLE
make a really useful readme file ...

### ISSUE THREAD

**Issue by VirgileVILE** [whitedragon0000/OpenBOR_PLUS#110]
I sincerely believe that it lacks clarity for less... gifted users.
I read this one, and it's been 48H that I'm still trying to figure out what the hell path Paks should be in on android. When I launch the app, it tries to show me the path, but only the beginning appears, so I have no idea of the architecture. I've tried to create a Paks folder in different places, but I've never been able to find the damn place read by the game. I don't understand this difference with teh old OpenBOR android port, especially since an “OpenBOR/Paks” folder at the root was sufficient...
Thanks in advance.

**Comment by whitedragon0000** [comment]
hello, sorry if the readme is not clear enough. in fact since the last migration the path changes for a question on android security policies.
the path is:
\storage\Android\media\org.openbor.engine\OpenBOR

**Comment by VirgileVILE** [comment]
Better late than never, thank you!
