### ISSUE TITLE
Contradictory license

### ISSUE THREAD

**Issue by Hechelion** [whitedragon0000/OpenBOR_PLUS#70]
Hi. I noticed that the license is 3-Clause BSD but in the readme you wrote "EXPRESSLY FORBIDDEN THE COPY OF THE "PLUS" CODE WITHOUT MY CONSENT."

You need change the readme or the license. Because you can not give permission to copy your code on one side and then on another side that can not copy it. This will generate confusion and misunderstandings and to avoid them it is better to clarify everything related to licenses and permits.
Remember that when placing a 3-clause BSD license, you are explicitly authorizing to use your code without having to contact you.

**Comment by whitedragon0000** [comment]
thank you to report me this issue.
Updated to BSD revised version and little changed readme.
