### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by nsw27** [whitedragon0000/OpenBOR_PLUS#78]
Hey WhiteDragon its good to see you are still working on Openbor and your engine variations are very interesting. 

I have a game that seems to be really good for testing limits of engine. I have tested Openbor and Openbor Plus (on PC and android) and whilst your version fixes a few things I am still having engine issues

My game has hundreds of enemies spawned at once, after a certain amount of enemies are on screen at once the game becomes slow until they are killed. these enemies appear as items that player collects (its based off a Gals panic mod)

Issues:
The next / level compete screen doesn't work and crashes game. (this is for PC, for android it works- is there a reason as to why ?) I have had to disable 'next' with my playthrough tests to uncover more issues...

game crashes when you pause and end game (occasionally on PC)

game crashes at end of completed set. (this is for PC, for android it works- is there a reason as to why ?)

if you have a scene to play at end of set it wont even play that and crashes after last level. (this is for PC, for android it works- is there a reason as to why ?)

Android version has slow down with more 'coin' on screen. example my Set 1 has no issues but every other set has bigger playing field and more 'coins' onscreen and has slowdown. set 2 is closest to set 1 in terms of size and once you collect enough coins the slowdown disappears. These same levels wont have slowdown on PC. 

[jelly.zip](https://github.com/whitedragon0000/OpenBOR_PLUS/files/2662129/jelly.zip)

Your help into these issues is greatly appreciated.

**Comment by whitedragon0000** [comment]
Hi @nsw27 and thanks, I worked especially on PS3 port!
Well, you have to pay attention to not exceed #define MAX_ENTS 150 in screen first.
You have to test to help me to know..
1) Try to increment MAX_ENTS 150 to X and re-compile the engine to test and report.
2) Build a version for debugger. So:
open makefile and under "ifdef BUILD_WIN" comment or delete line:
STRIP 	        = $(WINDEV)/$(PREFIX)strip$(EXTENSION) $(TARGET) -o $(TARGET_FINAL)

So when you build Win version you will be able to see a big exe file (~13MB).
Now set a environment variable to point to path: \tools\win-sdk\bin or simply copy exe to that directory
and the execute debbgger: gdb
then type "file OpenBOR.exe" or "target OpenBOR.exe" and the type "run".
Play to your mod and when you get the crash, you will able to see the exception into debugger console.
So then report the exception.

Thanks

**Comment by nsw27** [comment]
Oh I've never compiled engine before. I don't know how and I'm not too technical either lol.

So there is a cap if max entities ? I have well over 150 on screen at once so if there's a way to make that more like 400 or something that'd be awesome.

I'm keen to try ps3 port also. I have heaps of ps3 but none are.custom firmware... yet

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nsw27** [comment]
can you please explain how to compile engine. I have never done it before and do not know the step by step instructions required. I am not very technical so more detailed instructions the better :)


and thank you again for helping me, its hard to find good help these days

**Comment by nsw27** [comment]
I was shown by someone else how to compile engine so have been able to test engines. The issue with entities on screen cant seem to be resolved at this stage so I guess this can be closed.
