### ISSUE TITLE
Command Line Paths not working

### ISSUE THREAD

**Issue by TheExcitedTech** [whitedragon0000/OpenBOR_PLUS#89]
When using Command prompt to open an OpenBor compatible PAK with either a direct file path or from a directory that isn't in the /OpenBor/Paks directory; the application will briefly open and close. This occurs regardless if any options are used (fullscreen and keepaspectratio)

### Reproduce
EG OpenBOR application resides in "C:/Users/Administrator/Desktop/OpenBOR/openbor.exe." The PAK file is named "A.PAK" and lives  "C:/Users/Administrator/Desktop/A.pak" or "C:/Users/Administrator/Desktop/OpenBOR/A.pak"

You can place the binary in any directory and issue persists EG C:/OpenBOR or C:/Users/Admin/Desktop/

However

If the Pak file is in the /Paks directory of OpenBor you can open the PAK via "C:/Users/Administrator/Desktop/OpenBOR/Paks/A.pak" or 

"C:/Users/Administrator/Desktop/OpenBOR/openbor.exe" A.pak

### Expected behavior
Executing `"C:/Users/Administrator/Desktop/OpenBOR/openbor.exe" -fullscreen -keepaspectratio "C:/Users/Administrator/Desktop/A.pak"
` should load OpenBor and have it load A.Pak in Full Screen and maintaining the aspect ratio. As long as the file paths are correct it should be able to load OpenBor compatible PAK files no matter where the PAK file resides. 

### Version

Windows 10 
OpenBOR PLUS v3.0 Build 413

Thank you.

**Comment by whitedragon0000** [comment]
thank you for your report. Fixed from new release (build 462).
