### ISSUE TITLE
PS3 crashing on build 462

### ISSUE THREAD

**Issue by AdrianoADR** [whitedragon0000/OpenBOR_PLUS#90]
Hello. I use OpenBOR PLUS on my PS3 SuperSlim. I recently upgraded from build 413 to 462 and OpenBOR PLUS is crashing on the PAK selection screen. And when trying to exit homebrew through the HOME button on the controller, instead of the console returning to XMB it forces a soft reset of the system. In build 413 and earlier this did not happen.

This is the log from "OpenBorLog.txt" file:
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   214827008 Bytes (   204 MB )
 Used Ram:     8519680 Bytes (     8 MB )

Failed to load controls from /dev_hdd0/OpenBOR/Saves/default.controls
SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1
SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1

**Comment by whitedragon0000** [comment]
From the second-last (413) version the code related to gamepads has been rewritten. So I advise you to delete all files from the **Saves** folder in order to recreate the correct files for the latest version (462).
Thanks

**Comment by AdrianoADR** [comment]
> From the second-last (413) version the code related to gamepads has been rewritten. So I advise you to delete all files from the **Saves** folder in order to recreate the correct files for the latest version (462). Thanks

Good afternoon. I did what you suggested about doing a clean install of OpenBOR PLUS, without the folders previously created by build 413, and the newest build (462) still crashes the PS3.

**Comment by whitedragon0000** [comment]
Thanks, can you show me. The new log with cleaned saves?

**Comment by AdrianoADR** [comment]
Sorry for my delay. I did two tests with build 462: the first with just a single PAK file in the "paks" folder and OpenBOR automatically opened the game without any problems and the controls fully responsive. Homebrew did not crash when I closed the game, returning normally to XMB. This is the log generated in this test:

Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   214827008 Bytes (   204 MB )
 Used Ram:     8519680 Bytes (     8 MB )

SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1
OpenBoR v3.0 Build 462 (commit hash: 5f11193), Compile Date: Mar  6 2022

Game Selected: /dev_hdd0/OpenBOR/Paks/OB__Teenage_Mutant_Ninja_Turtles.pak

FileCaching System Init......	Enabled
Initializing video............
'data/video.txt' not found.
Initialized video.............	320x240 (Mode: 0)

SDL video Renderer: PSL1GHT 
Loading menu.txt.............	Done!
Loading fonts................	1 2 3 4 Done!
Timer init...................	Done!
Initialize Sound..............	
Loading sprites..............	Done!
Loading level order..........	Done!
Loading model constants......	Done!
Loading script settings......	Done!
Loading scripts..............	Done!
Loading models...............

Set up device: Standard Controller #3
Cacheing 'flash' from data/chars/misc/flash.txt
Cacheing 'knife' from data/chars/misc/knife.txt
Cacheing 'star' from data/chars/misc/star.txt
Cacheing 'moinho' from data/chars/misc/moinho.txt
Cacheing 'leo' from data/chars/leo/leo.txt
Cacheing 'mikey' from data/chars/mikey/mikey.txt
Cacheing 'don' from data/chars/don/don.txt
Cacheing 'raph' from data/chars/raph/raph.txt
Cacheing '1up' from data/chars/misc/1up.txt
Cacheing 'pizza' from data/chars/misc/pizza.txt
Cacheing 'bonus' from data/chars/misc/bonus.txt
Cacheing 'fbuck' from data/chars/misc/fbuck.txt
Cacheing 'roadblk' from data/chars/misc/roadblk.txt
Cacheing 'metalhd' from data/chars/metalhd/metalhd.txt
Cacheing 'ratking' from data/chars/ratking/ratking.txt
Cacheing 'rockst' from data/chars/rockst/rockst.txt
Cacheing 'baxter' from data/chars/baxter/baxter.txt
Cacheing 'bebop' from data/chars/bebop/bebop.txt
Cacheing 'casey' from data/chars/casey/casey.txt
Cacheing 'letherhd' from data/chars/letherhd/letherhd.txt
Cacheing 'tokka' from data/chars/tokka/tokka.txt
Cacheing 'rahzar' from data/chars/rahzar/rahzar.txt
Cacheing 'slashe' from data/chars/slash/slashe.txt
Cacheing 'ftelite' from data/chars/ftelite/ftelite.txt
Cacheing 'krang' from data/chars/krang/krang.txt
Cacheing 'destru' from data/chars/destru/destru.txt
Cacheing 'bigmouse' from data/chars/bigmouse/bigmouse.txt
Cacheing 'moto' from data/chars/auto/moto.txt
Cacheing 'mouser' from data/chars/mouser/mouser.txt
Cacheing 'boxer' from data/chars/boxer/boxer.txt
Cacheing 'fly' from data/chars/fly/fly.txt
Cacheing 'foot' from data/chars/foot/foot.txt
Cacheing 'footaxe' from data/chars/footaxe/footaxe.txt
Cacheing 'foothmr' from data/chars/foothmr/foothmr.txt
Cacheing 'footsp' from data/chars/footsp/footsp.txt
Cacheing 'footn' from data/chars/footn/footn.txt
Cacheing 'footn2' from data/chars/footn2/footn2.txt
Cacheing 'footsw' from data/chars/footsw/footsw.txt
Cacheing 'foothk' from data/chars/foothk/foothk.txt
Cacheing 'foottri' from data/chars/foottri/foottri.txt
Cacheing 'rock' from data/chars/rock/rock.txt
Cacheing 'rock2' from data/chars/rock/rock2.txt
Cacheing 'roadkill' from data/chars/roadkill/roadkill.txt

Loaded 'flash' from data/chars/misc/flash.txt 
Loaded 'Leo' from data/chars/leo/leo.txt 
Loaded 'Mikey' from data/chars/mikey/mikey.txt 
Loaded 'Don' from data/chars/don/don.txt 
Loaded 'Raph' from data/chars/raph/raph.txt 

Loading models...............	Done!
Object engine init...........	Done!
Input init...................	Set up device: Standard Controller #1
Done!
Caching backgrounds..........	Done!
Create blending tables.......	Done!
Save settings so far........	Done!


use cached bg
use cached bg
use cached bg
use cached bg
Level Loading:   'data/levels/roof.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   205266944 Bytes (   195 MB )
 Used Ram:    18079744 Bytes (    17 MB )

Loaded 'fbuck' from data/chars/misc/fbuck.txt 
Loaded 'pizza' from data/chars/misc/pizza.txt 
Loaded 'bonus' from data/chars/misc/bonus.txt 
Loaded 'foot' from data/chars/foot/foot.txt 
Loaded 'foottri' from data/chars/foottri/foottri.txt 
Loaded 'star' from data/chars/misc/star.txt 
Loaded 'footn' from data/chars/footn/footn.txt 
Loaded 'footsw' from data/chars/footsw/footsw.txt 
Loaded 'foothk' from data/chars/foothk/foothk.txt 
Loaded 'metalhd' from data/chars/metalhd/metalhd.txt 
Loaded 'mouser' from data/chars/mouser/mouser.txt 

Level Loaded:    'data/levels/roof.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   204218368 Bytes (   194 MB )
 Used Ram:    19128320 Bytes (    18 MB )
Total sprites mapped: 404

Level Unloading: 'data/levels/roof.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   204218368 Bytes (   194 MB )
 Used Ram:    19128320 Bytes (    18 MB )

RAM Status:
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   204218368 Bytes (   194 MB )
 Used Ram:    19128320 Bytes (    18 MB )

use cached bg
use cached bg

************ Shutting Down ************

OpenBOR v3.0 Build 462 (commit hash: 5f11193), Compile Date: Mar  6 2022
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   204218368 Bytes (   194 MB )
 Used Ram:    19128320 Bytes (    18 MB )

Release level data...........
Done!

Release graphics data..........	Done!
Release game data............

Unload 'flash' ............Done.
Unload 'Leo' ............Done.
Unload 'Mikey' ............Done.
Unload 'Don' ............Done.
Unload 'Raph' ............Done.
Unload 'fbuck' ............Done.
Unload 'pizza' ............Done.
Unload 'bonus' ............Done.
Unload 'foot' ............Done.
Unload 'foottri' ............Done.
Unload 'star' ............Done.
Unload 'footn' ............Done.
Unload 'footsw' ............Done.
Unload 'foothk' ............Done.
Unload 'metalhd' ............Done.
Unload 'mouser' ............Done.

Release game data............	Done!
Release timer................	Done!
Release input hardware.......	Done!
Release sound system.........	Done!
Release FileCaching System...	Done!

**************** Done *****************

OpenBOR v3.0 Build 462 (commit hash: 5f11193), Compile Date: Mar  6 2022
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.


In the second test I put 2 PAKs files in the "paks" folder and OpenBOR crashed at the game selection screen forcing a soft reset after trying to exit homebrew via the HOME button on the controller. This is the log generated in this test:

Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   214827008 Bytes (   204 MB )
 Used Ram:     8519680 Bytes (     8 MB )

SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1
SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1


Apparently, build 462 is not able to manage the listing of games with several PAKs files in the "paks" folder. With a PAK only, OpenBOR PLUS works without problems.

**Comment by whitedragon0000** [comment]
I managed to reproduce the bug !! This is a great place to start. The bug is not related to a list of games but is related to the buttons from pplayer 2 onwards. If you only insert one pad it should go. So now I have to continue the investigation ..

**Comment by whitedragon0000** [comment]
here you can find the different versions with their dates. Could you test them for me and tell me which one works and which one doesn't, please?
https://www.mediafire.com/file/vmu10clc2ahvof8/ps3_test_vers.zip/file

**Comment by AdrianoADR** [comment]
> here you can find the different versions with their dates. Could you test them for me and tell me which one works and which one doesn't, ple

> I was unable to reproduce the bug. I am currently running as an emulator. I'll compile some executables so I can understand which build works and which doesn't. Would you help me?

Of course. 👍

**Comment by AdrianoADR** [comment]
> here you can find the different versions with their dates. Could you test them for me and tell me which one works and which one doesn't, please? https://www.mediafire.com/file/vmu10clc2ahvof8/ps3_test_vers.zip/file

I'll do the tests and in about an hour I'll give you an answer.

**Comment by AdrianoADR** [comment]
Good evening. I tested all 5 builds, and during the whole test I kept 2 PAK files in the "Paks" folder on my PS3. All builds worked perfectly, except the "2021-07-22.pkg" build. It has the same issues as build 462. As the log files are kind of long I zipped them and hosted at the following link:
https://drive.google.com/file/d/1CvODNnDHi6NUSoGpcVpr7QifsYCGRSK-

**Comment by whitedragon0000** [comment]
big thanks, I'm working on the fix

**Comment by whitedragon0000** [comment]
Found issue and fixed!! It was a game controller bug.
New tag and release version at: [Releases](https://github.com/whitedragon0000/OpenBOR_PLUS/releases/tag/v1.469)
Really big thanks for report, patience and your time!

**Comment by AdrianoADR** [comment]
Good evening. I did the same test as before on this new build (469) and it worked perfectly. Thank you very much for your attention and for porting OpenBOR to PlayStation 3. Just for the record, this is the log generated by build 469. Thanks again 👍:

Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   214827008 Bytes (   204 MB )
 Used Ram:     8519680 Bytes (     8 MB )

Loaded mapping for Standard Controller #1
SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1
SDL video Renderer: PSL1GHT 
Set up device: Standard Controller #1
OpenBoR v4.0 Build 469 (commit hash: 9852f91), Compile Date: May  2 2022

Game Selected: /dev_hdd0/OpenBOR/Paks/OB__BOR_-_Bots_Of_Rage.pak

Loaded mapping for Standard Controller #1
FileCaching System Init......	Enabled
Initializing video............
'data/video.txt' not found.
Initialized video.............	320x240 (Mode: 0)

SDL video Renderer: PSL1GHT 
Loading menu.txt.............	Done!
Loading fonts................	1 2 3 4 Done!
Timer init...................	Done!
Initialize Sound..............	
Loading sprites..............	Done!
Loading level order..........	Done!
Loading model constants......	Done!
Loading script settings......	Done!
Loading scripts..............	Done!
Loading models...............

Set up device: Standard Controller #3
Cacheing 'flash' from data/chars/misc/flash.txt
Cacheing 'robot_a' from data/chars/robot_a/robot_a.txt
Cacheing 'robot_b' from data/chars/robot_b/robot_b.txt
Cacheing 'bonus' from data/chars/misc/bonus.txt
Cacheing '1up' from data/chars/misc/1up.txt
Cacheing 'energia' from data/chars/misc/energia.txt
Cacheing 'boss01' from data/chars/boss01/boss01.txt
Cacheing 'boss02' from data/chars/boss02/boss02.txt
Cacheing 'boss03' from data/chars/boss03/boss03.txt
Cacheing 'boss04' from data/chars/boss04/boss04.txt
Cacheing 'boss05' from data/chars/boss05/boss05.txt
Cacheing 'boss06' from data/chars/boss06/boss06.txt
Cacheing 'boss07' from data/chars/boss07/boss07.txt
Cacheing 'boss08' from data/chars/boss08/boss08.txt
Cacheing 'boss09' from data/chars/boss09/boss09.txt
Cacheing 'boss10' from data/chars/boss10/boss10.txt
Cacheing 'robot01' from data/chars/robot01/robot01.txt
Cacheing 'robot02' from data/chars/robot02/robot02.txt
Cacheing 'robot03' from data/chars/robot03/robot03.txt
Cacheing 'robot04' from data/chars/robot04/robot04.txt
Cacheing 'robot05' from data/chars/robot05/robot05.txt
Cacheing 'robot06' from data/chars/robot06/robot06.txt
Cacheing 'robot07' from data/chars/robot07/robot07.txt
Cacheing 'robot08' from data/chars/robot08/robot08.txt
Cacheing 'robot09' from data/chars/robot09/robot09.txt
Cacheing 'robot10' from data/chars/robot10/robot10.txt
Cacheing 'robot11' from data/chars/robot11/robot11.txt
Cacheing 'robot12' from data/chars/robot12/robot12.txt
Cacheing 'robot13' from data/chars/robot13/robot13.txt
Cacheing 'robot14' from data/chars/robot14/robot14.txt
Cacheing 'robot15' from data/chars/robot15/robot15.txt
Cacheing 'robot16' from data/chars/robot16/robot16.txt
Cacheing 'robot17' from data/chars/robot17/robot17.txt
Cacheing 'robot18' from data/chars/robot18/robot18.txt
Cacheing 'robot19' from data/chars/robot19/robot19.txt
Cacheing 'robot20' from data/chars/robot20/robot20.txt
Cacheing 'robot21' from data/chars/robot21/robot21.txt
Cacheing 'robot22' from data/chars/robot22/robot22.txt
Cacheing 'robot23' from data/chars/robot_b/robot23.txt

Loaded 'flash' from data/chars/misc/flash.txt 
Loaded '_' from data/chars/robot_a/robot_a.txt 
Loaded '__' from data/chars/robot_b/robot_b.txt 

Loading models...............	Done!
Object engine init...........	Done!
Input init...................	Set up device: Standard Controller #1
Done!
Caching backgrounds..........	Done!
Create blending tables.......	Done!
Save settings so far........	Done!


use cached bg
use cached bg
use cached bg
use cached bg
use cached bg
Level Loading:   'data/levels/01.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   203169792 Bytes (   193 MB )
 Used Ram:    20176896 Bytes (    19 MB )

Loaded 'energia' from data/chars/misc/energia.txt 
Loaded 'bonus' from data/chars/misc/bonus.txt 
Loaded 'robot01' from data/chars/robot01/robot01.txt 
Loaded 'robot02' from data/chars/robot02/robot02.txt 
Loaded 'robot04' from data/chars/robot04/robot04.txt 
Loaded 'robot09' from data/chars/robot09/robot09.txt 
Loaded 'robot10' from data/chars/robot10/robot10.txt 
Loaded 'boss01' from data/chars/boss01/boss01.txt 

Level Loaded:    'data/levels/01.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )
Total sprites mapped: 285

Level Unloading: 'data/levels/01.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

RAM Status:
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

Level Loading:   'data/levels/02.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

Loaded '1up' from data/chars/misc/1up.txt 
Loaded 'robot06' from data/chars/robot06/robot06.txt 
Loaded 'robot14' from data/chars/robot14/robot14.txt 
Loaded 'robot17' from data/chars/robot17/robot17.txt 
Loaded 'robot20' from data/chars/robot20/robot20.txt 
Loaded 'boss02' from data/chars/boss02/boss02.txt 

Level Loaded:    'data/levels/02.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   201072640 Bytes (   191 MB )
 Used Ram:    22274048 Bytes (    21 MB )
Total sprites mapped: 426

Level Unloading: 'data/levels/02.txt'
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

RAM Status:
Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

use cached bg
use cached bg

************ Shutting Down ************

OpenBOR v4.0 Build 469 (commit hash: 9852f91), Compile Date: May  2 2022
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.

Total Ram:   223346688 Bytes (   213 MB )
 Free Ram:   202121216 Bytes (   192 MB )
 Used Ram:    21225472 Bytes (    20 MB )

Release level data...........
Done!

Release graphics data..........	Done!
Release game data............

Unload 'flash' ............Done.
Unload '_' ............Done.
Unload '__' ............Done.
Unload 'energia' ............Done.
Unload 'bonus' ............Done.
Unload 'robot01' ............Done.
Unload 'robot02' ............Done.
Unload 'robot04' ............Done.
Unload 'robot09' ............Done.
Unload 'robot10' ............Done.
Unload 'boss01' ............Done.
Unload '1up' ............Done.
Unload 'robot06' ............Done.
Unload 'robot14' ............Done.
Unload 'robot17' ............Done.
Unload 'robot20' ............Done.
Unload 'boss02' ............Done.

Release game data............	Done!
Release timer................	Done!
Release input hardware.......	Done!
Release sound system.........	Done!
Release FileCaching System...	Done!

**************** Done *****************

OpenBOR v4.0 Build 469 (commit hash: 9852f91), Compile Date: May  2 2022
Presented by the OpenBOR Team.
www.chronocrash.com
OpenBOR is the open source continuation of Beats of Rage by Senile Team.

Special thanks to SEGA and SNK.
