### ISSUE TITLE
GameCube Controller Support [Wii Port]

### ISSUE THREAD

**Issue by 60fpshacksrock** [whitedragon0000/OpenBOR_PLUS#91]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support for the GameCube controller on the Wii Port

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by whitedragon0000** [comment]
Thank you for your pull request. Gamecube controller added + Wii U Pro controller + Rumble support.

**Comment by 60fpshacksrock** [comment]
Thanks!
