### ISSUE TITLE
Request For A PSVita Port

### ISSUE THREAD

**Issue by MadZiontist** [whitedragon0000/OpenBOR_PLUS#95]
**Is your feature request related to a problem? Please describe.**

Request for a port to the PSVita platform.

**Describe the solution you'd like**

A working port to the PSVita with continued updates going forward.

**Describe alternatives you've considered**

There's was a port of the regular version of OpenBOR to the PSVita, but it was a one-off that only had one or two updates, and it has poor compatibility for the most part.

**Additional context**

**Comment by whitedragon0000** [comment]
Hi, I'm sorry but I won't be handling support for sony vita
