### ISSUE TITLE
controls mapping

### ISSUE THREAD

**Issue by RogerBrMG** [whitedragon0000/OpenBOR_PLUS#96]
Hello, I would like to know if you plan to add changes to the control on android, as I press to put the jump button on A but it does not change. ![Screenshot_20230219-122952_OpenBOR.jpg](https://user-images.githubusercontent.com/125814380/219958012-657d3ead-b417-499e-a22f-999437ada156.jpg)

**Comment by whitedragon0000** [comment]
Hi, please test this pre-release version:
[https://we.tl/t-wSX66bGlVZ](https://we.tl/t-wSX66bGlVZ)
Thanks

**Comment by RogerBrMG** [comment]
> Hi, please test this pre-release version:
> [https://we.tl/t-wSX66bGlVZ](https://we.tl/t-wSX66bGlVZ)
> Thanks

The problem has been solved with this version, thank you very much.

**Comment by whitedragon0000** [comment]
Version TAGGED. Thank you.
