### ISSUE TITLE
Android - Unable to Install Build 520 After Uninstalling Build 516

### ISSUE THREAD

**Issue by GumbyXGames** [whitedragon0000/OpenBOR_PLUS#98]
Please complete the following template to help us investigate your issue. Developer time is very limited - incomplete issue reports may be ignored and deleted.

**Note:** Legacy builds are not supported. Any fixes will be applied to the latest engine builds.

## Description
When I attempted to upgrade from build 516 to 520, I received an error message stating the was a package conflict (see attached screenshot). I uninstalled build 516 but kept app data since I was going to install build 520. I now get the same package conflict error message no matter what release of OpenBOR or OpenBOR Plus I try to install. 

### Reproduce
Provide step by step instructions to reproduce the behavior. Include any text files, scripts, etc., along with the engine log. In some cases, we may need a download link to your entire module:
1. Uninstall Build 516 but keep app data
2. Try to install any other release of OpenBOR or OpenBOR Plus. 

### Expected behavior
The app should install without issue. 

### Screenshots
![Screenshot_20230419-083353](https://user-images.githubusercontent.com/82996624/233076310-479b619b-f46c-4ed6-afbd-4eb81b915c4f.png)

### Version

- Platform: Android 
- Engine Build: 520 and 516

## Additional context
I believe the conflict may be caused by OpenBOR Plus using the same application name and version number in the app Manifest.

I have manually deleted any remaining app data for _org.openbor.engine_ from my devic. 

The easiest way I have found to resolve this issue is to reinstall the last version of the application (516 in this case) then uninstall it along with any app data or build the application with a unique name.

**Comment by whitedragon0000** [comment]
Thank you so much for your feedback and support.
The code will be changed by new versions

**Comment by GumbyXGames** [comment]
So I'm just stuck not being able to is OpenBOR+ until you release a new version?

**Comment by GumbyXGames** [comment]
I was able to resolve the issue. Somehow the app wasn't completely uninstalled. I had to go through ADB to uninstall the remaining bits of the package.
