### ISSUE TITLE
Android Gamepad mapping

### ISSUE THREAD

**Issue by Arkwelder** [whitedragon0000/OpenBOR_PLUS#99]
Please complete the following template to help us investigate your issue. Developer time is very limited - incomplete issue reports may be ignored and deleted.

**Note:** Legacy builds are not supported. Any fixes will be applied to the latest engine builds.

## Description
Provide a clear and concise description of what the bug is here.
The Android controller setup bug is still present on my device. I am using a wired F310 gamepad on an OPi5 with Android 12 installed. The controller is recognized and works fine. I am able to navigate menus and all games appear to work flawlessly. However, I am unable to remap controls in the appropriate menu.
### Reproduce
Provide step by step instructions to reproduce the behavior. Include any text files, scripts, etc., along with the engine log. In some cases, we may need a download link to your entire module:
1. Load stage '...'
2. Entity in  '....' positon.
3. Use  '....' move while '....'.
Load Game. Options>Control Options>Setup Player 1.
### Expected behavior
When pressing the Attack/A button, three dots (...) should appear user should be able remap button. Instead, even though a sound is heard but buttons cannot be remapped. 

### Version
Please provide the SPECIFIC version the issue first appeared. This is very important, it is nearly impossible for us to pour through the entire code base to find singular issues without a starting point.

- Platform: Android
- Engine Build: Build 520

**Comment by whitedragon0000** [comment]
Hi, thanks for your issue.
There is a SDL bug on android.
BTW I fixed this issue in the [latest release](https://github.com/whitedragon0000/OpenBOR_PLUS/releases/tag/v1.526).
